version: "2"
volumes:
  tailscale:

services:
  tailscale:
    image: tailscale/tailscale:v1.38.4
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_EXTRA_ARGS: --hostname="${TS_HOSTNAME}"
      TS_SOCKET: /var/run/tailscale/tailscaled.sock
    depends_on:
      - nginx
    volumes:
      - tailscale:/var/run/tailscale
  caddy:
    image: caddy:2.6.4-alpine
    user: "0"
    command: caddy reverse-proxy --from ${TS_HOSTNAME}.${TS_TAILNET_NAME} --to nginx:8337
    restart: always
    network_mode: service:tailscale
    volumes:
      - tailscale:/var/run/tailscale
    depends_on:
      - nginx
